# Generated by Django 5.1.4 on 2025-01-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Courses',
        ),
    ]
