# Generated by Django 5.1.4 on 2025-01-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('what_you_learn', models.TextField()),
                ('courses_included', models.TextField()),
                ('course_contents', models.TextField()),
                ('detailed_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_headings', to='adminUser.course')),
            ],
        ),
        migrations.CreateModel(
            name='TitleHeadingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('title_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='adminUser.titleheading')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
