# Generated by Django 5.1.4 on 2025-01-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0004_course_titleheading_titleheadingdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleheadingdetail',
            name='title_heading',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='adminUser.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='TitleHeading',
        ),
        migrations.DeleteModel(
            name='TitleHeadingDetail',
        ),
    ]
