# Generated by Django 5.1.4 on 2025-01-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0010_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Mobile_Number',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
