# Generated by Django 5.1.4 on 2025-01-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0011_remove_contactus_email_contactus_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='Mobile_Number',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='None', max_length=255),
        ),
    ]
