# Generated by Django 5.1.4 on 2025-01-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotliteApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
